workflows:
  android-build-only:
    name: Android Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Install Flutter Dependencies
        script: |
          flutter pub get
      - name: Build App Bundle (AAB)
        script: |
          flutter build appbundle --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
  ios-build-only:
    name: iOS Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter Dependencies
        script: |
          flutter pub get
      - name: Build iOS App
        script: |
          flutter build ipa --release --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
