workflows:
  android-deploy-workflow:
    name: Android Deployment Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    triggering:
      events:
        - tag
      cancel_previous_builds: true
    environment:
      groups:
        - google_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Setup the keystore
        script: |
          # Decode and save the keystore file
          echo $KEYSTORE_FILE | base64 --decode > $CM_BUILD_DIR/android/app/uploads-keystore.jks

          # Create the key.properties file
          cat > $CM_BUILD_DIR/android/key.properties << EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEY_PASSWORD
          keyAlias=$KEY_ALIAS
          storeFile=$CM_BUILD_DIR/android/app/uploads-keystore.jks
          EOF
      - name: Build AAB
        script: |
          flutter pub get
          flutter build appbundle --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal

  android-build-only:
    name: Android Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      groups:
        - google_credentials
      flutter: stable
    scripts:
      - name: Setup the keystore
        script: |
          echo $KEYSTORE_FILE | base64 --decode > $CM_BUILD_DIR/android/app/uploads-keystore.jks
          cat > $CM_BUILD_DIR/android/key.properties << EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEY_PASSWORD
          keyAlias=$KEY_ALIAS
          storeFile=$CM_BUILD_DIR/android/app/uploads-keystore.jks
          EOF
      - name: Build App Bundle (AAB)
        script: |
          flutter pub get
          flutter build appbundle --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab

  ios-build-only:
    name: iOS Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter Dependencies
        script: flutter pub get
      - name: Build iOS App
        script: flutter build ipa --release --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
