workflows:
  android-build-only:
    name: Android Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      groups:
        - google_credentials
      flutter: stable
    scripts:
      - name: Install Flutter Dependencies
        script: |
          flutter pub get
      - name: Build App Bundle (AAB)
        script: |
          flutter build appbundle --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
    scripts:
      - name: Setup the keystore
        script: |
          echo $KEYSTORE_FILE | base64 --decode > /Users/macbookair/uploads-keystore.jks
          cat >> "$CM_BUILD_DIR/android/key.properties" << EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEYSTORE_KEY_PASSWORD
          keyAlias=upload
          storeFile=/Users/macbookair/uploads-keystore.jks
          EOF

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true

  ios-build-only:
    name: iOS Build Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter Dependencies
        script: |
          flutter pub get
      - name: Build iOS App
        script: |
          flutter build ipa --release --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
