# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# android/fastlane/Fastfile
default_platform(:android)

platform :android do
  # Upload the AAB already built by Flutter to Google Play
  desc "Upload release AAB to Google Play (no Gradle build here)"
  lane :deploy do
    upload_to_play_store(
      track: 'production',               # or 'internal' for safer first runs
      package_name: 'com.zakipay.teencard',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key_file: '/tmp/play_key.json',  # we create this in the GH Action
      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_metadata: true
    )
  end
end
