default_platform(:android)

platform :android do
  desc "Upload release AAB to Google Play (no Gradle build here)"
  lane :deploy do
    upload_to_play_store(
      track: 'production',                      # or 'internal'
      package_name: 'com.zakipay.teencard',
      aab: '../build/app/outputs/bundle/release/app-release.aab',

      # ✅ Correct key parameter for modern fastlane
      json_key: '/tmp/play_key.json',

      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_metadata: true
    )
  end
end
