name: Deploy to Google Play

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'  # Update if needed

      - name: Install dependencies
        run: flutter pub get

      - name: Build release AAB
        run: flutter build appbundle --release

      - name: Decode Google Play Key
        run: echo "${{ secrets.GOOGLE_PLAY_JSON_KEY }}" | base64 -d > /tmp/play_key.json

      - name: Deploy with Fastlane
        run: |
          cd android
          bundle install || gem install bundler && bundle install
          fastlane deploy
        env:
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
